# This is a basic workflow that is manually triggered

name: Arduino build workflow

# controls actions to run on pull request or change to main branch
on: [push, pull_request]

# A workflow to validate if arduino code will compile 
jobs:
  build:
    name: Test compiling for UNO
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v3
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: arduino/report-size-deltas@v1